# Site settings
author: Lena
title: ruby
header-img: img/home-bg.png
email: lenahou2013@gmail.com
copyright_name: Lena
description: > # this means to ignore newlines until "baseurl:"
  A Ruby Beginner's Study Notes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lena0128

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
